### ISSUE TITLE
[SFP-refactor] xcvrd crashes while trying to read CMIS passive cables

### ISSUE THREAD

**Issue by aravindmani-1** [Azure/sonic-platform-common#234]
**Trace Logs:**
>>> c.get_sfp(1).get_transceiver_info()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/dist-packages/sonic_platform_base/sonic_xcvr/sfp_optoe_base.py", line 24, in get_transceiver_info
    return api.get_transceiver_info() if api is not None else None
  File "/usr/local/lib/python3.7/dist-packages/sonic_platform_base/sonic_xcvr/api/public/cmis.py", line 106, in get_transceiver_info
    admin_info = self.xcvr_eeprom.read(consts.ADMIN_INFO_FIELD)
  File "/usr/local/lib/python3.7/dist-packages/sonic_platform_base/sonic_xcvr/xcvr_eeprom.py", line 30, in read
    return field.decode(raw_data, **decoded_deps)
  File "/usr/local/lib/python3.7/dist-packages/sonic_platform_base/sonic_xcvr/fields/xcvr_field.py", line 237, in decode
    **decoded_deps)
  File "/usr/local/lib/python3.7/dist-packages/sonic_platform_base/sonic_xcvr/fields/xcvr_field.py", line 150, in decode
    decoded = struct.unpack(self.format, raw_data)[0]
struct.error: unpack requires a buffer of 1 bytes

Issue was not seen for 400G AOC cables.
**Note:** 
The same module was read without any issues when SFP refactor is not included.

**Comment by aravindmani-1** [comment]
@prgeor @qinchuanares Please take a look at it.

**Comment by prgeor** [comment]
thanks @aravindmani-1
